### ISSUE TITLE
Gui closes after starting with display

### ISSUE THREAD

**Issue by jstam89** [belzebalex/wargames#1]
Traceback (most recent call last):
  File "c:/pythontest/n.soldiers/main.py", line 24, in <module>
    dis = Display(sys.argv[2])
  File "c:\pythontest\n.soldiers\display.py", line 28, in __init__
    self.soldiers = pickle.load(f)
_pickle.UnpicklingError: could not find MARK

**Comment by alextousss** [comment]
Hello,

A quick google search gets me here: https://stackoverflow.com/questions/35879096/pickle-unpicklingerror-could-not-find-mark

Could you try the attached and tell me whether it works? I'll fix it if it does.

Thank you,
